[package]
name = "syphon-payload-server"
version = "0.1.0"
edition = "2021"

[dependencies]
# Web Frameworks
actix-web = "4"
axum = "0.6"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
hex = "0.4"
uuid = { version = "1", features = ["v4"] }

# Networking
reqwest = { version = "0.11", features = ["json"] }
tower-http = { version = "0.4", features = ["cors"] }

# 🧩 FHE Library (modern Zama TFHE)
tfhe = { version = "0.5", features = ["integer", "seeder_unix"] }
